app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui.html

clients:
  scrapper:
    host: http://localhost:8080

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
